spring:
  profiles.active: local
server:
  port: 8881

---
spring:
  profiles: local
  aop:
    auto: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    url: jdbc:mysql://dohko.mysql.001.master.hualala.com:3306/db_shop?autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false&allowMultiQueries=true&statementInterceptors=brave.mysql.TracingStatementInterceptor
    username: myshopdev
    password: mydev@pwd
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 5
    max-active: 30
    min-idle: 2
    validation-query: SELECT 1
    test-on-borrow: true
    test-while-idle: true

  #不加此配置，会报：org.springframework.amqp.AmqpConnectException: java.net.ConnectException: Connection refused: connect
  rabbitmq:
    username: guest
    password: guest
    host: 172.16.0.29
    port: 5672

redis:
    host: 172.16.32.132
    port: 6379
    db: 3
    pool:
      maxActive: 100
      maxIdle: 100
      minIdle: 80
      maxWait: 10000
